# Generated by Django 2.2 on 2019-04-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190417_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(max_length=1000),
        ),
    ]
