# Generated by Django 2.2 on 2019-04-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190418_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerGroupInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrackerGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrackerGroup'),
        ),
        migrations.DeleteModel(
            name='NameGroup',
        ),
        migrations.AddField(
            model_name='response',
            name='tracker_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.TrackerGroupInstance'),
        ),
    ]
