# Generated by Django 2.2 on 2019-04-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190419_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='tracker_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrackerGroupInstance'),
        ),
    ]
