# Generated by Django 2.2 on 2019-04-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190419_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['tracker', 'order']},
        ),
    ]
