# Generated by Django 2.2 on 2019-04-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190419_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.TrackerGroup'),
        ),
        migrations.AlterField(
            model_name='trackergroupinstance',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackergroupinstance',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_instances', to='core.TrackerGroup'),
        ),
    ]
