# Generated by Django 2.2 on 2019-04-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190423_1508'),
        ('core', '0012_auto_20190423_1628'),
    ]

    operations = [
    ]
