# Generated by Django 2.2 on 2019-04-23 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190423_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='set active'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question', verbose_name='assign question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='set active'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(verbose_name='order your question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.TrackerGroup', verbose_name='assign tracker'),
        ),
        migrations.AlterField(
            model_name='trackergroup',
            name='active',
            field=models.BooleanField(default=True, verbose_name='set active'),
        ),
        migrations.AlterField(
            model_name='trackergroup',
            name='available_to',
            field=models.ManyToManyField(related_name='available_trackers', to=settings.AUTH_USER_MODEL, verbose_name='assign users'),
        ),
        migrations.AlterField(
            model_name='trackergroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='tracker name'),
        ),
    ]
