# Generated by Django 2.2 on 2019-04-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20190424_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackergroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trackergroupinstance',
            options={},
        ),
    ]
