# Generated by Django 2.2 on 2019-04-25 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190424_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='name',
            new_name='question_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='tracker_question',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='answered_for',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='trackergroupinstance',
            old_name='start',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trackergroup',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trackergroup',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='trackergroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trackergroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trackergroupinstance',
            name='end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_family_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='label',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='trackergroup',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
