# Generated by Django 2.2 on 2019-04-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190424_1303'),
        ('core', '0014_auto_20190424_2212'),
    ]

    operations = [
    ]
