# Generated by Django 2.2 on 2019-04-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190425_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='answer',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trackergroup',
            old_name='users',
            new_name='user',
        ),
    ]
