# Generated by Django 2.2 on 2019-04-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190425_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_answer',
            new_name='current_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tracker_question',
            new_name='current_question',
        ),
    ]
