# Generated by Django 2.2 on 2019-04-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190427_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackergroupinstance',
            options={'ordering': ['started_at']},
        ),
    ]
