# Generated by Django 2.2 on 2019-04-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190428_0956'),
        ('core', '0017_auto_20190427_1913'),
    ]

    operations = [
    ]
